### ISSUE TITLE
I think this crawler is blocked. Is it right?

### ISSUE THREAD

**Issue by feel940** [huaying/ins-crawler#6]
The results of using your code are as follows:

> Strating fetching...
Number of fetched posts: 0
Wait for 1 sec...
Number of fetched posts: 0
Wait for 2 sec...
Number of fetched posts: 0
Wait for 4 sec...
Number of fetched posts: 0
Wait for 8 sec...
Number of fetched posts: 0
Wait for 16 sec...
Number of fetched posts: 0
Wait for 32 sec...
Number of fetched posts: 0
Wait for 64 sec...
Number of fetched posts: 0
Wait for 128 sec...
Number of fetched posts: 0
Wait for 256 sec...
Number of fetched posts: 0
Wait for 512 sec...
Done. Fetched 0 posts.

**Comment by huaying** [comment]
Thanks for the report. It failed due to the change of Instagram's website. I already fixed it.
